### PR TITLE
Clean up log messages of the PAM module

### PR DESCRIPTION
**Pull request by marlam**
This series of trivial patches cleans up the syslog messages of the PAM module, by changing the log level of some messages to something more appropriate, and by introducing an optional 'debug' flag to the PAM module so that debug messages are only logged when this flag is present.

### CODE REVIEW

**Comment by mrvanes** [comment]
Thank you very much for your PR, but could you please fix the missing line test code coverage in `config.c`?

**Comment by marlam** [comment]
I'd love to, but unfortunately I cannot find out which line that is.
The codecov link above gives me a generously multicolored `config.c`, but it does not tell me which line it means.
Frankly I don't even know what "coverage" means in this context -- covered by what?

**Comment by mrvanes** [comment]
Since I can't mess with your source tree, I created a branch that adds a test to cover the cache_duration=0 case that your new code touches and gets a penalty for adding an untested line. You can add those changes to your tree and the coverage should improve or at least stay the same, I hope:
https://github.com/SURFscz/pam-weblogin/commit/23e214bfdc04e408dbf4ccfb46924be393517fb2

**Comment by marlam** [comment]
I added your commit to the pull request.

Thank you very much for taking the time to explain the coverage issue and providing a new test.

**Pull request merged**
